<!DOCTYPE computer_components [
<!ELEMENT computer_components (component+)>
<!ELEMENT component (name, brand, model)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
]>
<computer_components>
  <component>
    <name>Processor</name>
    <brand>Intel</brand>
    <model>Core i7</model>
  </component>
  <component>
    <name>Graphics Card</name>
    <brand>NVIDIA</brand>
    <model>GeForce RTX 3080</model>
  </component>
  <component>
    <name>Memory</name>
    <brand>Corsair</brand>
    <model>Vengeance RGB Pro</model>
  </component>
  <component>
    <name>Storage</name>
    <brand>Samsung</brand>
    <model>970 EVO Plus</model>
  </component>
  <component>
    <name>Motherboard</name>
    <brand>ASUS</brand>
    <model>ROG Strix Z590-E Gaming</model>
  </component>
</computer_components>
